import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import  ThemeProvider  from '@/providers/ThemeProvider'
import NextTopLoader from 'nextjs-toploader'
import { ThemeToggleButton } from '@/components/ThemeToggleButton'
import TanstackProvider from '@/providers/TanstackProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <TanstackProvider>
          <ClerkProvider>
              <NextTopLoader showSpinner={false} />
              <ThemeToggleButton className="absolute top-4 right-6 z-50"  />
              <body className={inter.className}>{children}</body>
          </ClerkProvider>
        </TanstackProvider>
      </ThemeProvider>
    </html>
  )
}
